
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.hss.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MARGIN = 12;
  public static final int DOC = 22;
  public static final int BUTTON = 5;
  public static final int ENDDOC = 23;
  public static final int RBRACE = 16;
  public static final int PADDING = 13;
  public static final int IMAGE = 6;
  public static final int WIDTH = 7;
  public static final int COLOR = 9;
  public static final int SECTION = 3;
  public static final int LBRACE = 15;
  public static final int ID = 18;
  public static final int WITH = 14;
  public static final int STRING = 19;
  public static final int EQUALS = 17;
  public static final int NUMBER = 21;
  public static final int PAGE = 2;
  public static final int EOF = 0;
  public static final int HEIGHT = 8;
  public static final int error = 1;
  public static final int HEX_COLOR = 20;
  public static final int FONT_SIZE = 11;
  public static final int TEXT = 4;
  public static final int BACKGROUND = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAGE",
  "SECTION",
  "TEXT",
  "BUTTON",
  "IMAGE",
  "WIDTH",
  "HEIGHT",
  "COLOR",
  "BACKGROUND",
  "FONT_SIZE",
  "MARGIN",
  "PADDING",
  "WITH",
  "LBRACE",
  "RBRACE",
  "EQUALS",
  "ID",
  "STRING",
  "HEX_COLOR",
  "NUMBER",
  "DOC",
  "ENDDOC"
  };
}

